Script	::= Route Script
		  | ε

Route		::= id ':' RouteBody
RouteBody	::= RouteLine RouteBody
			  | RouteLine
RouteLine	::= Lnav AltitudeOpt SpeedOpt
			  | 'via' airway


id		:= [A-Z]+
airway	:= [ABRGVTJQ]\d+
int		:= \d+